### ISSUE TITLE
Chore: Create SQL scripts to import data from at least 3 master resumes

### ISSUE THREAD

**Issue by souljorn** [dacabdi/simoorg#105]
**DUE DATE: 3/11/2019**

## SPECIFICATIONS
**As a** developer **I want to**add data from the master resumes to the database **so that** testing of the application will become easier.

### Acceptance Criteria
-  [x] Create a CSV file with all the data
-  [x] Import the data using DataGrip
-  [x] Have Datagrip create all the SQL queries
-  [x] Add the queries to a migration script so the data is on every instance of the database
-  [x] Export JSON Formats of the data to be used in postman 

### Developer Notes

Created sql scripts to populate the database with mock data. This can be turned on and off by commenting out the line `COPY ./mockdata/sql/ /docker-entrypoint-initdb.d/
` in the docker file for the mysql container. There are also JSON file versions of the sql data as well. Finally there are CSV of each table incase the data needs to be added or edited, which can be easily done in most mysql IDE's like Workbench or Datagrip. The JSON data can be used for creating new tests or to understand the shape of the data in the database.

**Comment by dacabdi** [comment]
@souljorn a suggestion, to keep things clean and decoupled, what is your take on putting the data seeding sql scripts in a separate directory, lets say `sql/dataseed`. Adding another Docker directive to the MySQL `Dockerfile`, lets say `COPY ./dataseed/ /docker-entrypoint-initdb.d/, would then ensure the files are used on initializing the db. This way, disabling/enabling dataseeding is just about commenting a line in the Dockerfile. Furthermore, it keeps apart schema changing SQL from data SQL. What's your take?

**Comment by souljorn** [comment]
> @souljorn I have a suggestion in order to keep things clean and decoupled. What is your take on putting the data seeding SQL scripts in a separate directory, lets say `sql/dataseed`. Adding another Docker directive to the MySQL `Dockerfile`, lets say `COPY ./dataseed/ /docker-entrypoint-initdb.d/`, would then ensure the files are used on initializing the db. This way, disabling/enabling data seeding is just about commenting a line in the Dockerfile. Furthermore, it keeps apart schema changing SQL from data SQL. What's your take?

I think that is simple solution when we need to turn off seeding of data.
