### ISSUE TITLE
UI: Create/Edit Company form

### ISSUE THREAD

**Issue by technocharpie** [dacabdi/simoorg#62]
**DUE DATE: 02/*/2019**

## SPECIFICATIONS (@by dacabdi)
**As a** front-end developer **I want to** have a *Create/Edit Company* form **so that** the user can create and edit *Company* entities.

### Acceptance Criteria
- Form fields (as provided by the wireframes)
  - [x] *Company Name* text input field
  - [x] if *Edit* mode, include a hidden form field for *id*
  - [x] *cancel* button to leave the form
- Validation
  - [x] *Company Name* is **required** .
- Interaction
  - [x] Request (using the id) and load Company values into the form when opening in *Edit* mode
  - [x] Modify all inputs according to current mode
  - [x] If loaded as *Edit* the form must submit the request along with a numeric company id
  - [x] If loaded as *Create*, on submission, the form must expect an id and a confirmation of creation from the backend
  - [x] Display errors and warnings according to request

#### Development

Any subdir on the root of the repo should be named following conventions, all lowercase, words separated by dashes. Include a `.gitignore` rules for this part of the project.

Follow the validation rules laid out on the *Acceptance Criteria* items.

The form should be prepared to be loaded under any window or page, it should show up on *Create/Edit* mode and follow the request scheme explained in the *Acceptance Criteria* section. 

If the form is rendered to create a *Company*, it should appear with all fields blanked out (only placeholders). The request should not include an id, but **MUST** expect one along with a confirmation from the backend.

If the form is rendered to edit a *Company*, it should appear with all fields filled out with the corresponding information. The request **MUST** include an id that the frontend obtained from the backend upon receiving the data model for editing. Most likely, this id was the one used to retrieve the entity. A confirmation should be received from the backend upong editing.

Display errors and warnings as appropiate before sending requests or on receiving requests. **Please remember that validations must happen both on client and server side.** This is why even after validating on the frontend field input, we must confirm with backend and display error and warning dialogs or signals.

#### Consider the following sources
- [Material Design Tools](https://material.io/tools/)
- [Material Design Design](https://material.io/design/)

## ANALYSIS AND DEVELOPMENT (by @technocharpie)

Add any appropiate *Analysis and Development* notes.

---

## TESTS (by @technocharpie)
|Given|When|Then|
|---|---|---|
|A *Company* form loaded for creation with all fields validated|Submit is clicked|The server responds with an OK and the id of the newly created *Company*|
|A *Company* form|It is loaded in creation mode|The labels on the title must indicate to the user that the form is in creation mode|
|A *Company* form loaded for creation with all fields validated|Submit is clicked and the server responds with an error|A dialog or signal of error is displayed to the user|
|A *Company* form loaded for creation|The user inputs a non valid (see validation section) value in *Company Name*|The UI disables the *submit* button|
|A *Company* form loaded for creation|The user leaves *Company Name* empty|The UI disables the *submit* button|
|A *Company* form|It is loaded on editing mode|All the fields are filled with the *Company* data (including the id hidden field!)|
|A *Company* form|It is loaded in editing mode|The labels on the title must indicate to the user that the form is in editing mode|
|A *Company* form loaded for editing with all fields validated|Submit is clicked|The server responds with an OK|
|A *Company* form loaded for editing|The user inputs a non valid (see validation section) value in *Company Name*|The UI disables the *submit* button|
|A *Company* form loaded for editing with all fields validated|Submit is clicked and the server responds with an error|A dialog or signal of error is displayed to the user|

**Comment by dacabdi** [comment]
@technocharpie you are getting the hang of this :1st_place_medal:
