### ISSUE TITLE
Add Repeating Section Content Control creation and substitution 

### ISSUE THREAD

**Issue by dacabdi** [dacabdi/simoorg#7]
**As a** a developer **I want to** fill and create MS Word Repeating Section Content Control elements **so that** arrays and data collections can be parsed into the document.

## Analysis
The document is looped through looking for content controls with the **tag** of the Repeating Content Control we want to duplicate. The retrieved `sdtElement` is cloned and the identification properties(tags, titles, etc.) are changed to avoid collisions in the identification attributes. The cloned element is appended to the parent element of the original Repeating Content Control. (`firstElement.Parent.Append(clonedElement)`). 

This looping is repeated as many times as new elements we need. Each new element is created upon the last one, making it possible to populate them as they are being duplicated.

## Tests
|| Given || When || Then ||
|| A repeating content control with formatting || Multiplied || The formatting remains untouched ||  
|| A document with repeating content controls || Content controls are multiplied || The document format remains the same ||
|| A document without repeating content controls(or content controls with the tag of the expected repeating content control) || Program is run || The document suffers no change ||

**Comment by Jcabza008** [comment]
In the Analysis and Development of this issue the following is stated : *We should consider adding a numeric suffix to the tag attribute*, this should be edited based on the fact that this is indeed the current method used to avoid *collisions in the identification attributes*.

**Comment by Jcabza008** [comment]
@dacabdi Please check ^
